---
# ansible-playbook ~/work/ansible/playbooks/p_f5_run_command.yml --vault-password-file ~/work/ansible/vault_password_ruisampaio

- name: F5 Run Command
  gather_facts: no
  hosts: localhost
  vars_files:
    - ~/work/ansible/vault/vault_rs.yml
  vars:
    f5: "{{ f5 }}"
    f5_user: "{{ f5_user }}"
  
  collections:
    - f5networks.f5_modules


  tasks:

    - name: debug fact f5_partition
      debug:
        msg:
          - F5: "{{ f5 }}"
          - F5 User: "{{ f5_user }}"

    # - name: Collect all BIG-IP information 
    #   bigip_device_info:
    #     gather_subset:
    #       # - all
    #       # - irules
    #       # - ltm-pools
    #       - nodes
    #       # - partitions
    #       # - vcmp-guests
    #       # - virtual-addresses
    #       # - virtual-servers
    #       # - vlans
    #       # - "{{ subset }}"
    #     provider:
    #       server: "{{ f5 }}"
    #       user: "{{ f5_user }}"
    #       password: "{{ f5_password }}"
    #       validate_certs: no
    #   register: info
    #   delegate_to: localhost

    - name: Collect  BIG-IP nodes 
      bigip_device_info:
        gather_subset:
          - nodes
        provider:
          server: "{{ f5 }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no
      register: info
      delegate_to: localhost

    - name: debug info
      debug:
        var: info

 



# ===========================================================================================

  # - name: run commands
  #   bigip_command:
  #     commands: 
  #       - show sys version
  #       - list ltm virtual
  #     provider:
  #       server: "{{ f5 }}"
  #       user: "{{ f5_user }}"
  #       password: "{{ f5_password }}"
  #       validate_certs: no
  #   register: command_output
  #   delegate_to: localhost

  # - name: debug command_output
  #   debug:
  #     var: command_output.stdout_lines


  # - name: run msh show ltm virtual detail
  #   bigip_command:
  #     commands: 
  #       - tmsh show ltm virtual detail
  #     provider:
  #       server: "{{ f5 }}"
  #       user: "{{ f5_user }}"
  #       password: "{{ f5_password }}"
  #       validate_certs: no
  #     chdir: "{{ f5_partition }}"
  #   register: command_output2
  #   delegate_to: localhost

  # - name: debug command_output
  #   debug:
  #     var: command_output2.stdout_lines


# ===========================================================================================


