---

- name: Run command
  hosts: "{{ p_hosts}}"
  tasks:
 
  - name: Ping linux server
    ansible.builtin.ping:
    register: ping_output
    when: ansible_os_family == "RedHat"

  - name: debug linux ping_output
    debug:
      var: ping_output
    when: ansible_os_family == "RedHat"

  - name: Ping windows server
    ansible.windows.win_ping:
    register: ping_output
    when: ansible_os_family == "Windows"

  - name: debug windows ping_output
    debug:
      var: ping_output
    when: ansible_os_family == "Windows"